package es.urjc.sd.p1;

/* ********************************************************************* */
import java.time.LocalDate;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;


/* ********************************************************************* */
/**
 * A class to model an bycicle station of the system.
 */
@Entity
public class Station {
    /* Attributes */
    /**
     * Unique identifier of an station. 
     * Automatically generated when a new station is registered in the system.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int identifier;

    /**
     * A secondary identifier for an station. 
     * Autogenerated in creation.
     */
    @GeneratedValue(strategy = GenerationType.AUTO)
    private int serial_number;

    /**
     * A set of coordinates to locate an station in Earth planet.
     * Latitude first.
     * Longitude second.
     */
    private Coordinate coordinates; 

    /**
     * Attribute to indicate how many bicycles can store an station.
     * It has 2 fixed values: 5 or 10.
     * It values can not be changed.
     */
    private int capacity;

    /**
     * Attribute to indicate if an station is active in the system. It will function as a "soft" delete in the system.
     * true: Active Station.
     * false: Inactive station a.k.a station "deleted"
     * Set to Active automatically on creation.
     */
    private boolean status;

    /**
     * Attribute to store when an station was registered in the system.
     * Format: YYYY/MM/DD => Year, Month, Day.
     * Will be asignated automatically when the station was registered.
     * It will store the actual date IN THE SERVER.
     */
    private LocalDate installDate;

    /* ********************************************************************* */
    /* Builders */
    /**
     * Necessary builder to load from Database.
     */
    public Station(){

    }

    /**
     * Default builder for an Station object.
     * @param coor The coordinates of the station. Latitude first, Longitude second.
     * @param cap The capacity of the station, either 5 or 10.
     */
    public Station(Float[] coor, int cap){
        this.coordinates = new Coordinate(coor[0], coor[1]);
        this.capacity = cap;
        this.installDate = LocalDate.now();
        this.status = true;
    }

    /* ********************************************************************* */
    /* Getter & Setter */
    /**
     * Getter for Identifier attribute.
     * @return the identifier of a bycicle station.
     */
    public Integer getIdentifier(){
        return this.identifier;
    }

    // No setter needed for identifier attribute, can not changed.


    /**
     * Getter for the serial number attribute.
     * @return The serial number of a bycicle station.
     */
    public Integer getSerialNumber(){
        return this.serial_number;
    }

    // No setter needed for serial number attribute, can not be changed.


    /**
     * Getter for coorfinates attribute.
     * @return The coordinates where an station is located.
     */
    public Coordinate getCoordinate(){
        return this.coordinates;
    }

    /**
     * Setter for coordinates attribute
     * @param coor New set of coordinates of a bycicle station.
     */
    public void setCoordinate(Float[] coor){
        this.coordinates = this.getCoordinate().edit(coor);
    }


    /**
     * Getter for Capacity attribute.
     * @return The capacicy of a bycicle station.
     */
    public Integer getCapacity(){
        return this.capacity;
    }

    // No setter needed for capacity, can not be changed.


    /**
     * Getter for status attribute.
     * @return if a bycicle station is active or inactive.
     */
    public Boolean getStatus(){
        return this.status;
    }

    public void setStatus(Boolean b){
        this.status = b;
    }


    /**
     * Getter for install date attribute.
     * @return When a bycicle station was installed.
     */
    public LocalDate getInstallDate(){
        return this.installDate;
    }

    // No setter needed for install date attribute, can not be changed.

    
    /* ********************************************************************* */
    /* Methods */


} // End class Station
